
family = "noto_handwriting-sbix"
output_file = "noto_handwriting-sbix.ttf"
color_format = "sbix"
clipbox_quantization = 32

[axis.wght]
name = "Weight"
default = 400

[master.regular]
style_name = "Regular"
srcs = ["../font-srcs/noto-emoji/svg/emoji_u270d.svg", "../font-srcs/noto-emoji/svg/emoji_u270d_1f3fb.svg", "../font-srcs/noto-emoji/svg/emoji_u270d_1f3fc.svg", "../font-srcs/noto-emoji/svg/emoji_u270d_1f3fd.svg", "../font-srcs/noto-emoji/svg/emoji_u270d_1f3fe.svg", "../font-srcs/noto-emoji/svg/emoji_u270d_1f3ff.svg"]

[master.regular.position]
wght = 400
